### ISSUE TITLE
Bool delegations do not work

### ISSUE THREAD

**Issue by melak** [mattp-/MooX-HandlesVia#7]
MooX::HandlesVia 0.001008, Data::Perl 0.002011, Moo 2.004000, Perl 5.30.3

```perl
#!/usr/bin/env perl

use strictures 2;
use 5.20.0;

package Foo {
    use Moo;
    use MooX::HandlesVia;

    has attr => (
        is => 'rw',
        handles_via => 'Bool',
        handles => {
            flip => 'set',
            flop => 'unset',
            flick => 'toggle',
        }
    );
}

my $p = Foo->new(attr => 1);
$p->flip; say $p->attr;
$p->flop; say $p->attr;
$p->flick; say $p->attr;

$p = Foo->new(attr => 0);
$p->flip; say $p->attr;
$p->flop; say $p->attr;
$p->flick; say $p->attr;
```

```bash
$ perl t.pl 
1
1
1
0
0
0
```

**Comment by tobyink** [comment]
Documentation says:

> Moo attribute method delegations are passed the attribute value. This is fine for references (objects, arrays, hashrefs..) it means simple scalar types are **READ ONLY**. This unfortunately means Number, String, Counter, Bool cannot modify the attributes value, rendering them largely useless.

You might have better luck with [Sub::HandlesVia](https://metacpan.org/pod/Sub::HandlesVia) which integrates with Moo in a more invasive way and gets read-write access to attributes. It is possible that MooX::HandlesVia will be deprecated in favour of Sub::HandlesVia.

**Comment by melak** [comment]
This must have slipped my comprehension, thank you very much. On to Sub::HandlesVia then.
